#!/usr/bin/env python3
"""Generate Grain's icon from one set of shapes: the Android adaptive-icon vectors, the website icons and a preview.

The shapes are the logo drawn in CSS on the download page (website/style.css .frame): a rounded camera body, a lens
ring and a small gold dot, in a 112 x 80 box. Needs Pillow (pip install pillow).

  python3 scripts/render_icon.py            # writes the vectors and the website icons
  python3 scripts/render_icon.py --preview /tmp/icon-preview.png
"""
import argparse
import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
DRAWABLE = ROOT / "app/src/main/res/drawable"
WEBSITE = ROOT / "website"

BACKGROUND = "#11110F"
BODY = "#6C634C"
LENS = "#B9A66E"
DOT = "#DBBD6E"

# The logo in its own 112 x 80 box: body corner radius, lens ellipse (centre and radii) and dot (centre and radius).
BOX_W, BOX_H, BODY_R = 112.0, 80.0, 16.0
LENS_C, LENS_RX, LENS_RY = (56.0, 40.0), 29.0, 26.0
DOT_C, DOT_R = (95.0, 16.0), 3.0

# Android adaptive icon: a 108dp canvas whose visible, safe part is a 66dp circle in the middle.
CANVAS, SAFE_RADIUS = 108.0, 33.0
APP_WIDTH = 56.0          # body width in dp
APP_STROKE = 1.8          # dp, body and lens
APP_DOT_R = 3.3           # a little bigger than the web dot so it survives small sizes


def number(value: float) -> str:
    return f"{value:.2f}".rstrip("0").rstrip(".")


def rounded_rect(x, y, w, h, r) -> str:
    n = number
    return (f"M{n(x + r)},{n(y)} H{n(x + w - r)} A{n(r)},{n(r)} 0 0 1 {n(x + w)},{n(y + r)} V{n(y + h - r)} "
            f"A{n(r)},{n(r)} 0 0 1 {n(x + w - r)},{n(y + h)} H{n(x + r)} A{n(r)},{n(r)} 0 0 1 {n(x)},{n(y + h - r)} "
            f"V{n(y + r)} A{n(r)},{n(r)} 0 0 1 {n(x + r)},{n(y)} Z")


def ellipse(cx, cy, rx, ry) -> str:
    n = number
    return f"M{n(cx - rx)},{n(cy)} A{n(rx)},{n(ry)} 0 1 0 {n(cx + rx)},{n(cy)} A{n(rx)},{n(ry)} 0 1 0 {n(cx - rx)},{n(cy)} Z"


def android_geometry():
    """The three shapes in the 108 x 108 viewport, plus the farthest distance any of them reaches from the centre."""
    s = APP_WIDTH / BOX_W
    w, h = BOX_W * s, BOX_H * s
    x, y = (CANVAS - w) / 2, (CANVAS - h) / 2
    body = rounded_rect(x, y, w, h, BODY_R * s)
    lens = ellipse(x + LENS_C[0] * s, y + LENS_C[1] * s, LENS_RX * s, LENS_RY * s)
    dot_c = (x + DOT_C[0] * s, y + DOT_C[1] * s)
    dot = ellipse(dot_c[0], dot_c[1], APP_DOT_R, APP_DOT_R)
    # The farthest point of the body is on a corner arc, not the sharp corner.
    corner = (w / 2 - BODY_R * s, h / 2 - BODY_R * s)
    reach = math.hypot(*corner) + BODY_R * s + APP_STROKE / 2
    return body, lens, dot, reach, (x, y, w, h, s, dot_c)


def vector_xml(body, lens, dot, colors, alphas=None) -> str:
    a = alphas or ("FF", "FF", "FF")
    c = [col.lstrip("#") for col in colors]
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/render_icon.py from the logo on the download page. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#00000000" android:strokeColor="#{a[0]}{c[0]}" android:strokeWidth="{APP_STROKE}" android:pathData="{body}" />
    <path android:fillColor="#00000000" android:strokeColor="#{a[1]}{c[1]}" android:strokeWidth="{APP_STROKE}" android:pathData="{lens}" />
    <path android:fillColor="#{a[2]}{c[2]}" android:pathData="{dot}" />
</vector>
'''


def draw_logo(size: int, width_fraction: float, background=BACKGROUND, min_stroke=0.0, body_color=BODY, scale=8) -> Image.Image:
    """The logo centred on a square canvas, drawn at [scale]x and reduced for smooth edges."""
    big = size * scale
    image = Image.new("RGB", (big, big), background)
    d = ImageDraw.Draw(image)
    w = big * width_fraction
    s = w / BOX_W
    h = BOX_H * s
    x, y = (big - w) / 2, (big - h) / 2
    stroke = max(round(w * APP_STROKE / APP_WIDTH), round(min_stroke * scale))
    d.rounded_rectangle((x, y, x + w, y + h), radius=BODY_R * s, outline=body_color, width=stroke)
    cx, cy = x + LENS_C[0] * s, y + LENS_C[1] * s
    d.ellipse((cx - LENS_RX * s, cy - LENS_RY * s, cx + LENS_RX * s, cy + LENS_RY * s), outline=LENS, width=stroke)
    px, py, pr = x + DOT_C[0] * s, y + DOT_C[1] * s, DOT_R * s * 1.15
    d.ellipse((px - pr, py - pr, px + pr, py + pr), fill=DOT)
    return image.resize((size, size), Image.LANCZOS)


def app_icon_preview(path: Path) -> None:
    """The adaptive icon (108dp canvas) shown through a circle and a rounded-square mask, plus the website icons."""
    unit = 5
    size = int(CANVAS * unit)
    canvas = draw_logo(size, APP_WIDTH / CANVAS, scale=3)
    visible = int(72 * unit)
    margin = (size - visible) // 2
    sheet = Image.new("RGB", (size * 2 + 60 + 260, size + 40), "#2a2a28")
    for index, shape in enumerate(("circle", "squircle")):
        mask = Image.new("L", (size, size), 0)
        md = ImageDraw.Draw(mask)
        box = (margin, margin, margin + visible, margin + visible)
        if shape == "circle":
            md.ellipse(box, fill=255)
        else:
            md.rounded_rectangle(box, radius=int(visible * 0.3), fill=255)
        tile = Image.new("RGB", (size, size), "#2a2a28")
        tile.paste(canvas, (0, 0), mask)
        sheet.paste(tile, (20 + index * (size + 20), 20))
    x, y = size * 2 + 60, 20
    for icon in (draw_logo(180, 0.72), draw_logo(64, 0.78, min_stroke=1.6, body_color="#8F8467"), draw_logo(32, 0.84, min_stroke=1.3, body_color="#8F8467")):
        sheet.paste(icon, (x, y))
        y += icon.height + 16
    sheet.paste(draw_logo(32, 0.84, min_stroke=1.3, body_color="#8F8467").resize((96, 96), Image.NEAREST), (x, y))
    sheet.save(path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--preview", type=Path, help="also write a preview sheet to this path")
    args = parser.parse_args()
    body, lens, dot, reach, _ = android_geometry()
    assert reach <= SAFE_RADIUS, f"the icon reaches {reach:.1f}dp from the centre, the safe zone is {SAFE_RADIUS}dp"
    print(f"Android icon: body {APP_WIDTH}dp wide, farthest point {reach:.1f}dp of {SAFE_RADIUS}dp safe radius")
    DRAWABLE.mkdir(parents=True, exist_ok=True)
    (DRAWABLE / "luma_launcher_foreground.xml").write_text(vector_xml(body, lens, dot, (BODY, LENS, DOT)), encoding="utf-8")
    # The themed (monochrome) icon is tinted by the system; different alphas keep the body quieter than the lens.
    (DRAWABLE / "luma_launcher_monochrome.xml").write_text(
        vector_xml(body, lens, dot, ("#FFFFFF", "#FFFFFF", "#FFFFFF"), alphas=("B3", "E6", "FF")), encoding="utf-8")
    for name, size, fraction, stroke, body_color in (("favicon-32.png", 32, 0.84, 1.3, "#8F8467"), ("apple-touch-icon.png", 180, 0.72, 0, BODY),
                                                     ("icon-192.png", 192, 0.72, 0, BODY), ("icon-512.png", 512, 0.72, 0, BODY)):
        draw_logo(size, fraction, min_stroke=stroke, body_color=body_color).save(WEBSITE / name, optimize=True)
    print("Wrote the adaptive-icon vectors and the website icons")
    if args.preview:
        app_icon_preview(args.preview)
        print("Preview:", args.preview)


if __name__ == "__main__":
    main()
